<a href="https://colab.research.google.com/github/roymeir/PyTorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor = torch.rand(7,7)
tensor

# Create random tensor


tensor([[0.1421, 0.9311, 0.2409, 0.0345, 0.5816, 0.2636, 0.7978],
        [0.3676, 0.9043, 0.9759, 0.0224, 0.4258, 0.8642, 0.8682],
        [0.7615, 0.3823, 0.4807, 0.4045, 0.0235, 0.5487, 0.5098],
        [0.7633, 0.8906, 0.4742, 0.4271, 0.3126, 0.7133, 0.0742],
        [0.3808, 0.6787, 0.4905, 0.0201, 0.0429, 0.8996, 0.0484],
        [0.4369, 0.3362, 0.8137, 0.0904, 0.8147, 0.1584, 0.3369],
        [0.7238, 0.7792, 0.2975, 0.6075, 0.1587, 0.2886, 0.5901]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.rand(1,7)
print(torch.matmul(tensor,tensor2.t()))

# Perform matrix multiplication


tensor([[1.5795],
        [2.1674],
        [1.4571],
        [1.8159],
        [1.2213],
        [1.6095],
        [1.7026]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
SEED = torch.manual_seed(0)

# Create two random tensors
randTensor1 = torch.rand(7,7)
randTensor2 = torch.rand(1,7)
print(torch.matmul(randTensor1,randTensor2.t()))

# Matrix multiply tensors


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    print("GPU is available")
    randTensor1 = torch.rand(2,3).to('cuda')
    randTensor2 = torch.rand(2,3).to('cuda')
else:
    print("GPU is not available")
    randTensor1 = torch.rand(2,3)
    randTensor2 = torch.rand(2,3)
# Create two random tensors on GPU
print(f"{randTensor1}\n{randTensor2}")

GPU is available
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
multipliedTensor = torch.mm(randTensor1, randTensor2.T)
print(multipliedTensor, multipliedTensor.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
print(f"Maximal element: {torch.max(multipliedTensor)}")
# Find min
print(f"Minimal element: {torch.min(multipliedTensor)}")

Maximal element: 0.5617256760597229
Minimal element: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
print(f"Maximal element index: {multipliedTensor.argmax()}")
# Find arg min
print(f"Minimal element index: {multipliedTensor.argmin()}")

Maximal element index: 3
Minimal element index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
randTensor = torch.rand(1,1,1,10)
# Remove single dimensions
squeezed_randTensor = randTensor.squeeze()

# Print out tensors and their shapes
print(randTensor,randTensor.shape)
print(f"\n{squeezed_randTensor} {squeezed_randTensor.shape}")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
