<a href="https://colab.research.google.com/github/roymeir/PyTorch/blob/main/firstPyTorchNoteBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Working With Tensors

In [ ]:
TENSOR = torch.tensor([[[[1,2,3,4,5],
                         [6,7,8,9,10]]],
                       [[[1,2,3,4,5],
                         [6,7,8,9,10]]]])
TENSOR.shape

torch.Size([2, 1, 2, 5])

In [ ]:
rando = torch.rand(3,4,6,2)
rando

tensor([[[[0.3994, 0.7010],
          [0.1845, 0.4102],
          [0.7001, 0.8420],
          [0.4943, 0.3376],
          [0.1652, 0.6444],
          [0.1615, 0.3805]],

         [[0.2929, 0.1560],
          [0.9870, 0.2600],
          [0.1615, 0.8820],
          [0.5683, 0.8339],
          [0.0364, 0.7625],
          [0.1803, 0.1812]],

         [[0.0262, 0.4778],
          [0.6629, 0.6629],
          [0.3680, 0.8439],
          [0.6557, 0.1816],
          [0.2619, 0.4689],
          [0.4409, 0.4974]],

         [[0.8322, 0.0894],
          [0.1467, 0.5312],
          [0.4099, 0.7694],
          [0.3968, 0.5932],
          [0.1050, 0.9031],
          [0.4443, 0.9955]]],


        [[[0.4443, 0.2340],
          [0.1748, 0.4492],
          [0.9387, 0.0938],
          [0.5592, 0.1852],
          [0.5504, 0.1746],
          [0.5181, 0.1721]],

         [[0.1160, 0.5107],
          [0.4030, 0.9169],
          [0.8811, 0.2009],
          [0.5082, 0.6024],
          [0.5597, 0.3952],
        

In [ ]:
check = torch.arange(start = 0,end = 10000, step = 19)
# check
# check.ndim(), check.size(),
check.shape

torch.Size([527])

In [ ]:
zeroes = torch.zeros_like(check)
zeroes.shape

torch.Size([527])

In [ ]:
float32_tensor = torch.rand(3, 3, 2, dtype=torch.float32, device="cpu")

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor * float32_tensor)

tensor([[[8.8344e-01, 3.2294e-01],
         [6.1488e-01, 3.9257e-01],
         [1.3444e-04, 7.1600e-01]],

        [[3.1632e-01, 4.9780e-02],
         [2.4420e-01, 2.6342e-01],
         [8.3480e-01, 6.6803e-01]],

        [[8.5355e-01, 1.5524e-01],
         [6.4677e-01, 3.8323e-01],
         [7.4947e-01, 1.6579e-02]]])


In [ ]:
# playing with tensor characteristics
someTensor = torch.rand(3,4)
someTensor

tensor([[0.5945, 0.9419, 0.2530, 0.9321],
        [0.8087, 0.5861, 0.1921, 0.9378],
        [0.2173, 0.7336, 0.1099, 0.5868]])

In [ ]:
print(f"Tensor data type: {someTensor.dtype}")
print(f"Tensor size: {someTensor.shape}")
print(f"Tensor device: {someTensor.device}")

Tensor data type: torch.float32
Tensor size: torch.Size([3, 4])
Tensor device: cpu


In [ ]:
someTensor = someTensor.to('')
print(f"Tensor device: {someTensor.device}")

RuntimeError: ignored

In [ ]:
import time

matrix = torch.rand(3, 4, 2, 5)

reshaped_matrix = matrix.view(3, 4, 10)
print(matrix)
print(reshaped_matrix)
# start_time = time.time()
# result = torch.matmul(matrix, reshaped_matrix)
# end_time = time.time()

# execution_time = end_time - start_time
# print("Execution time:", execution_time, "seconds")


tensor([[[[0.8983, 0.5510, 0.9239, 0.2078, 0.7975],
          [0.6528, 0.8820, 0.6822, 0.6111, 0.7590]],

         [[0.3328, 0.9163, 0.0263, 0.0604, 0.6721],
          [0.1560, 0.8172, 0.3487, 0.5379, 0.2683]],

         [[0.5088, 0.1225, 0.9387, 0.8676, 0.3709],
          [0.2232, 0.2067, 0.0058, 0.0176, 0.7778]],

         [[0.1118, 0.3827, 0.8855, 0.7514, 0.1802],
          [0.2247, 0.7528, 0.1331, 0.3433, 0.7027]]],


        [[[0.2550, 0.5589, 0.1995, 0.2859, 0.4317],
          [0.5768, 0.1575, 0.5178, 0.2376, 0.9073]],

         [[0.3916, 0.0111, 0.6018, 0.9094, 0.9452],
          [0.5073, 0.9227, 0.5317, 0.4684, 0.8840]],

         [[0.8131, 0.9277, 0.3308, 0.3251, 0.2221],
          [0.1908, 0.7259, 0.0258, 0.3137, 0.4769]],

         [[0.4876, 0.5315, 0.9483, 0.9647, 0.1621],
          [0.7864, 0.1188, 0.2201, 0.8129, 0.6636]]],


        [[[0.8070, 0.0941, 0.5583, 0.9169, 0.8417],
          [0.7908, 0.1295, 0.9681, 0.4163, 0.6640]],

         [[0.0695, 0.5902, 0.1144, 0.3650,

In [ ]:
torch.matmul(torch.rand(13,15), torch.rand(15,2))

tensor([[4.1411, 4.5663],
        [1.8887, 2.9105],
        [2.9049, 3.3856],
        [3.3553, 4.0213],
        [2.9009, 2.8299],
        [3.6211, 3.8187],
        [3.7788, 4.5758],
        [3.0524, 4.1584],
        [4.3399, 4.6897],
        [4.5101, 4.4361],
        [3.1943, 3.9673],
        [3.7992, 3.5547],
        [2.6897, 3.3091]])

In [ ]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])

print(stacked_tensor)
print(stacked_tensor.shape)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [ ]:
import torch

tensor = torch.arange(12)  # 1-dimensional tensor with 12 elements
print(f"original tensor: {tensor}")
# Using reshape()
reshaped_tensor = tensor.reshape(3, 4)
# reshaped_tensor will have shape (3, 4)
print(f"reshape tensor: {reshaped_tensor}")
# Using view()
viewed_tensor = tensor.view(3, 4)
# viewed_tensor will have shape (3, 4)
print(f"viewed tensor: {viewed_tensor}")
# Reshaping with inference
reshaped_inferred = tensor.reshape(2, -1)
# reshaped_inferred will have shape (3, 4)
print(f"reshape inferred: {reshaped_inferred}")
# Viewing with inference (raises an error)
viewed_inferred = tensor.view(6, -1)
# Raises a RuntimeError: Invalid argument 2: size '[-1 x 4]' is invalid for input with 12 elements
print(f"viewed inferred: {viewed_inferred}")

viewed_inferred += 5
print(f"viewed_inferred after adding: {viewed_inferred}")
print(f"OG tensor after adding: {tensor}")

reshaped_inferred += 5
print(f"reshaped_inferred after adding: {reshaped_inferred}")
print(f"OG tensor after adding: {tensor}")
print(f"viewed_inferred after adding: {viewed_inferred}")

original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshape tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
viewed tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
reshape inferred: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
viewed inferred: tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
viewed_inferred after adding: tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]])
OG tensor after adding: tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])
reshaped_inferred after adding: tensor([[10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21]])
OG tensor after adding: tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
viewed_inferred after adding: tensor([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
  

In [ ]:
stacked = torch.stack([tensor,tensor], dim = -2)
stacked

tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))
print(y, y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])


In [ ]:
x = torch.rand(size=(224,224,3))
x_permuted = x.permute(2,0,1)
print(x)
print(f"\n{x_permuted}\n")
x[0,0,0] = 13000
print(x)
print(f"\n{x_permuted}")

tensor([[[0.6458, 0.7156, 0.3595],
         [0.4199, 0.5890, 0.4028],
         [0.3632, 0.5160, 0.5688],
         ...,
         [0.2928, 0.5037, 0.4374],
         [0.4710, 0.7770, 0.0539],
         [0.7365, 0.6270, 0.5950]],

        [[0.3553, 0.4384, 0.6882],
         [0.7860, 0.1848, 0.6753],
         [0.1463, 0.8327, 0.9086],
         ...,
         [0.5383, 0.7824, 0.9777],
         [0.6526, 0.9680, 0.4617],
         [0.4718, 0.5620, 0.7344]],

        [[0.3843, 0.8979, 0.3996],
         [0.8121, 0.7022, 0.1561],
         [0.4880, 0.1311, 0.9905],
         ...,
         [0.7673, 0.4892, 0.4630],
         [0.4070, 0.1071, 0.0506],
         [0.0681, 0.6742, 0.8284]],

        ...,

        [[0.9128, 0.4925, 0.3357],
         [0.6289, 0.4828, 0.8028],
         [0.4295, 0.3430, 0.0853],
         ...,
         [0.9169, 0.2367, 0.7957],
         [0.5971, 0.5091, 0.6070],
         [0.5410, 0.6448, 0.3959]],

        [[0.6589, 0.7177, 0.9580],
         [0.4940, 0.2153, 0.2047],
         [0.

In [ ]:
x = torch.arange(1,19).reshape(2,3,3)
x,x[0,:,1],x[0,1,:], x[:,1,:]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 tensor([2, 5, 8]),
 tensor([4, 5, 6]),
 tensor([[ 4,  5,  6],
         [13, 14, 15]]))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'